config/routes.rb
Rails.application.routes.draw do

  get 'contact', to: 'pages#contact'

  resources :projects do
    collection do
      get 'soretec', to: "projects#soretec"
      get 'archil', to: "projects#archil"
      get 'fermepc', to: "projects#fermepc"
      get 'ose', to: "projects#ose"
      get 'dmum', to: "projects#dmum"
      get 'equiperle', to: "projects#equiperle"
      get 'pelemele', to: "projects#pelemele"
    end
  end



root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :set_list, only: [:show]

  def show
  end

  def index
  end

  def new
  end

  def edit
  end

  def soretec
    @projects = Project.where(name: 'soretec')
  end

  def archil
    @projects = Project.where(name: 'archil')
  end

  def dmum
    @projects = Project.where(name: 'dmum')
  end

  def ose
    @projects = Project.where(name: 'ose')
  end

  def fermepc
    @projects = Project.where(name: 'fermepc')
  end

  def equiperle
    @projects = Project.where(name: 'equiperle')
  end

  def pelemele
    @projects = Project.where(name: 'pelemele')
  end

  def set_list
    @db_constants = YAML.load_file(Rails.root.join('config', 'constants.yml'))
    @list = @db_constants['projects'].keys
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

    <title>Graphiste Webdesigner | Celia Albano</title>
    <link rel="icon" type="image/png" href="favicon.png" />
    <!--[if IE]><link rel="shortcut icon" type="image/x-icon" href="favicon.ico" /><![endif]-->
    <!-- <link rel="icon" type="image/x-icon" href="/favicon.ico" /> -->
    <meta name="description" content="Celia Albano est une graphiste polyvalente capable de créer des identités visuelles supports de communication autant que des sites internet. #UnPeuDeFolie #Communication #WebDesign">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="css/style.css" type="text/css" media="screen"/>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet" media="all">

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> -->
    <link rel="icon" type="image/png" href="http://res.cloudinary.com/dusxpvpz7/image/upload/v1490695839/logo_w4whbz.png"/>


    <link href="https://fonts.googleapis.com/css?family=Palanquin" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">


  </head>

  <body>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>


</html>

app/views/pages/contact.html.erb
<div class="contact-wrapper">

  <div class="container">
    <div class="question text-center">
      <h2>Et si nous partagions une idée?</h2>
    </div>
    <div class="contact-info text-center">
      <h3>Celia Albano</h3>
      <h4>albano.celia@gmail.com</h4>
      <h4>06 26 76 34 65</h4>
    </div>
    <div class="adress text-center">
      <p>N'hésitez pas à me contacter, j'ai hâte de connaitre votre projet!</p>
    </div>
  </div>

</div>

app/views/pages/home.html.erb
<%= render 'shared/navbar' %>

<!-- bannière parallax -->
<div class="banner">
  <div id="scene" class="scene">

    <ul>


      <li class="layer plan1" data-depth="0.5">
        <img src="http://res.cloudinary.com/dusxpvpz7/image/upload/v1492784961/ellipses-px-1_x0zbvc.png">
      </li>

      <li class="layer plan2" data-depth="1">
        <img src="http://res.cloudinary.com/dusxpvpz7/image/upload/v1492784962/ellipses-px-2_q7nn53.png">
      </li>

       <li class="layer portrait" data-depth="0">
        <img src="http://res.cloudinary.com/dusxpvpz7/image/upload/v1502272996/portrait-web-bann_s9fe71.png" alt="photo portrait">
      </li>

      <li class="layer plan3" data-depth="1.5">
        <img src="http://res.cloudinary.com/dusxpvpz7/image/upload/v1492784962/ellipses-px-3_ycovco.png">
      </li>

      <li class="layer icone1" data-depth="0.5">
        <img src="http://res.cloudinary.com/dusxpvpz7/image/upload/v1501490978/icone-idee-texte_ra4eeu.png">
      </li>

      <li class="layer icone2" data-depth="0.5">
        <img src="http://res.cloudinary.com/dusxpvpz7/image/upload/v1501490978/icone-dessin-texte2_jkg5hv.png">
      </li>

      <li class="layer icone3" data-depth="0.5">
        <img src="http://res.cloudinary.com/dusxpvpz7/image/upload/v1499077369/icone-web-texte_ymhrpp.png">
      </li>

    </ul>

  </div>
</div>

<!-- javascript pour parallax -->

<script type="text/javascript" src="deploy/parallax.js"></script>
<script>
  var scene = document.getElementById("scene");
  var parallax = new Parallax(scene);
</script>


<!-- icones wrapper -->

<!-- <div class="text-center padded">
  <div class="container icones-wrapper">
    <div class=row>
      <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 icones">
          <img src="http://res.cloudinary.com/dusxpvpz7/image/upload/v1490695838/icone-idee_fope2y.png" alt="idea icon">
            <h2>Des idées</h2>
            <p>Vous accompagner dans votre stratégie de communication</p>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 icones">
          <img src="http://res.cloudinary.com/dusxpvpz7/image/upload/v1490695838/icone-dessin_dmzllm.png" alt="pen icon">
          <h2>De la technique</h2>
          <p>Mettre tout en oeuvre pour vous fournir des documents de communication à votre image</p>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 icones">
          <img src="http://res.cloudinary.com/dusxpvpz7/image/upload/v1490695838/icone-web_bpghlk.png" alt="computer icon">
          <h2>Du web</h2>
          <p>Développer votre site web et votre présence sur le net</p>
        </div>
    </div>
  </div>
</div> -->

<div class="container citation-wrapper no-padding">

    <div class=row>
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 text-center blue-col-1">
        <div class="tour-bulle text-center">
          <img src="http://res.cloudinary.com/dusxpvpz7/image/upload/v1501667983/Apropos-typo_liiidu.png">
          <h2>Mais au fait, de quoi s'agit-il?</h2>
        </div>
       <!-- Navigation -->
      <!--   <div class="navbar-wagon-right">
          <a href="#projets" class="nav-link-page">Projets</a>
          <a href="#contact" class="nav-link-page">Contact</a>
        </div> -->
      </div>
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 text-center white-col-1 icon-padding">
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="presentation text-center">
              <h1>Hello! Je suis <span class="colored">Graphiste</span> & <span class="colored">Webdesigner</span></h1>
             <!--  <h3>Laissons nous aller, imaginons de belles choses!</h3> -->
            </div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="services text-center">
              <h1>Ça veut dire que je crée des logos, des affiches, des flyers, je mets en page vos plaquettes, livrets tout ce qui pourra servir à votre communication. Et ce n'est pas tout! Je crée et développe aussi votre site internet. </h1>
            </div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="icon">
              <div class="col-xs-7">
                <div class="sweep-text">
                  <p>Chaque projet commence par une <span class="stressedout">réflexion</span> approfondie sur les <span class="stressedout">enjeux, la cible et la sensibilité</span> de l'entreprise</p>
                </div>
              </div>
              <div class="col-xs-5 sweep-icon">
                  <img src="http://res.cloudinary.com/dusxpvpz7/image/upload/v1490695838/icone-idee_fope2y.png" alt="idea icon">
              </div>
            </div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="icon">
              <div class="col-xs-7">
                <div class="sweep-text">
                  <p>Tout est mis sur <span class="stressedout">papier</span> dans un <span class="stressedout">gribouillage avancé et élégant</span> qui révélera un premier aperçu du résultat</p>
                </div>
              </div>
              <div class="col-xs-5 sweep-icon">
                <img src="http://res.cloudinary.com/dusxpvpz7/image/upload/v1490695838/icone-dessin_dmzllm.png" alt="pen icon">
              </div>
            </div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="icon">
              <div class="col-xs-7">
                <div class="sweep-text">
                  <p>Pour que l'idée de départ se matérialise en un bel et bulle <span class="stressedout">outil de communication</span> je passe par la magie de l'<span class="stressedout">informatique</span> et donne <span class="stressedout">vie au design</span> élaboré en votre compagnie</p>
                </div>
              </div>
              <div class="col-xs-5 sweep-icon">
                <img src="http://res.cloudinary.com/dusxpvpz7/image/upload/v1490695838/icone-web_bpghlk.png" alt="computer icon">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

</div>


<!-- exemple de projets -->

<div class="container project-wrapper no-padding" id="projets">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 green-col">
      <div class="tour-bulle text-center">
        <img src="http://res.cloudinary.com/dusxpvpz7/image/upload/v1501059253/Projets-typo_ep2qzn.png" alt="projets-typo">
        <h2>Un petit tour dans ma bulle ça vous dit?</h2>
      </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 project-col">
      <div class=row>
        <a href="projects/soretec.html">
          <div class="col-xs-12 card soretec no-padding">
            <div class="overlay-yellow">
              <div class="text text-center">
                <h2>PRINT</h2>
                <p>Idéntité visuelle / Mise en page
              </div>
            </div>
          </div>
        </a>
        <a href="projects/archil.html">
          <div class="col-xs-12 card archil no-padding">
            <div class="overlay-yellow">
              <div class="text text-center">
                <h2>PRINT</h2>
                <p>Identité visuelle</p>
              </div>
            </div>
          </div>
        </a>
      </div>
      <div class=row>
        <a href="projects/ose.html">
          <div class="col-xs-12 card ose no-padding">
            <div class="overlay-yellow">
              <div class="text text-center">
                <h2>PRINT</h2>
                <p>Identité visuelle</p>
              </div>
            </div>
          </div>
        </a>
        <a href="projects/dmum.html">
          <div class="col-xs-12 card dmum no-padding">
            <div class="overlay-yellow">
              <div class="text text-center">
                <h2>PRINT</h2>
                <p>Mise en page / Illustration / Poster
              </div>
            </div>
          </div>
        </a>
      </div>
      <div class=row>
        <a href="projects/fermepc.html">
          <div class="col-xs-12 card fermepc no-padding">
            <div class="overlay-yellow">
              <div class="text text-center">
                <h2>PRINT</h2>
                <p>Identité visuelle / Packaging</p>
              </div>
            </div>
          </div>
        </a>
        <a href="projects/pelemele.html">
          <div class="col-xs-12 card pelemele no-padding">
            <div class="overlay-yellow">
              <div class="text text-center">
                <h2>PRINT</h2>
                <p>Divers projets</p>
              </div>
            </div>
          </div>
        </a>
      </div>
    </div>
  </div>
</div>

<div class="container contact-wrapper no-padding" id="contact">

    <div class=row>
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 text-center blue-col">
        <div class="contact text-center">
          <img src="http://res.cloudinary.com/dusxpvpz7/image/upload/v1501059252/contact-typo_snsp3d.png" alt="contact-typo">
          <h2>Et si nous partagions une idée?</h2>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 text-center white-col">
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

            <ul class="bubbles">
              <li></li>
              <li></li>
              <li></li>
              <li></li>
              <li></li>
              <li></li>
              <li></li>
            </ul>

              <div class="contact-info text-center">
                <h3>Celia Albano</h3>
                <h4>albano.celia@gmail.com</h4>
                <h4>+33 6 26 76 34 65</h4>
              </div>
              <div id="top-head">
                <img src="http://res.cloudinary.com/dusxpvpz7/image/upload/v1502272996/portrait-web-bann_s9fe71.png" alt="portrait coupé">
              </div>

            <!-- <div class="adress text-center">
              <p>N'hésitez pas à me contacter, j'ai hâte de connaitre votre projet!</p>
            </div> -->
          </div>
        </div>
      </div>
    </div>

</div>

app/views/projects/archil.html.erb
<%= render 'shared/navbar-project' %>

<div class="body-project">

  <div class="container">

    <div class="row">
      <div class="col-xs-12, col-sm-12, col-md-4, col-lg-4 no-padding">
        <div class="photo-card-portrait" id="cdv-archil">
        </div>
      </div>
      <div class="col-xs-12, col-sm-12, col-md-4, col-lg-4 no-padding">
        <div class="work-description" id="logo-archil">
        </div>
      </div>
      <div class="col-xs-12, col-sm-12, col-md-4, col-lg-4 no-padding">
        <div class="work-description">
          <h2>ARCHI'L - Architecte Scénographe</h2>
          <h4>Création d'identité visuelle</h4>
          <p>- logo</p>
          <p>- carte de visite</p>
        </div>
      </div>
    </div>

  </div>

</div>

app/views/projects/dmum.html.erb
<%= render 'shared/navbar-project' %>

<div class="body-project">

  <div class="container">

    <div class="row">
      <div class="col-xs-12, col-sm-12, col-md-4, col-lg-4 no-padding">
        <div class="photo-card" id="logo-dmum">
        </div>
      </div>
      <div class="col-xs-12, col-sm-12, col-md-4, col-lg-4 no-padding">
        <div class="work-description">
          <h2>DESSINE MOI UN MOUTON</h2>
          <h4>Création de supports</h4>
          <p>- Roll up</p>
          <p>- poster</p>
          <h4>Mise en page et graphisme d'un livret</h4>
        </div>
      </div>
      <div class="col-xs-12, col-sm-12, col-md-4, col-lg-4 no-padding">
        <div class="photo-card" id="kake-dmum">
        </div>
      </div>
    </div>

    <div class="row">

      <div class="col-xs-12, col-sm-12, col-md-4, col-lg-4 no-padding">
        <div class="photo-card-portrait" id="poster-dmum">
        </div>
      </div>

      <div class="col-xs-12, col-sm-12, col-md-8, col-lg-8">

        <div class="row">
          <div class="col-xs-12, col-sm-12, col-md-6, col-lg-6 no-padding">
            <div class="work-description" id="couv-dmum">
            </div>
          </div>
          <div class="col-xs-12, col-sm-12, col-md-6, col-lg-6 no-padding">
            <div class="work-description" id="double3-dmum">
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-12, col-sm-12, col-md-6, col-lg-6 no-padding">
            <div class="photo-card" id="double1-dmum">
            </div>
          </div>
          <div class="col-xs-12, col-sm-12, col-md-6, col-lg-6 no-padding">
            <div class="photo-card" id="double2-dmum">
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/projects/fermepc.html.erb
<%= render 'shared/navbar-project' %>

<div class="body-project">

  <div class="container">

    <div class="row">
      <div class="col-xs-12, col-sm-12, col-md-4, col-lg-4 no-padding">
        <div class="photo-card" id="logo-fermepc">
        </div>
      </div>
      <div class="col-xs-12, col-sm-12, col-md-4, col-lg-4 no-padding">
        <div class="work-description">
          <h2>FERME PHILIPPE COMPIEGNE</h2>
          <h4>Création d'identité visuelle</h4>
          <p>- logo</p>
          <p>- étiquettes pour fromages</p>
        </div>
      </div>
      <div class="col-xs-12, col-sm-12, col-md-4, col-lg-4 no-padding">
        <div class="photo-card" id="glinglin-fermepc">
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12, col-sm-12, col-md-4, col-lg-4 no-padding">
        <div class="work-description" id="coeur-fermepc">
        </div>
      </div>
      <div class="col-xs-12, col-sm-12, col-md-8, col-lg-8 no-padding">
        <div class="work-description" id="fromages">
        </div>
      </div>

    </div>
  </div>
</div>

app/views/projects/index.html.erb
<%= render 'shared/navbar-project' %>

<div class="project-wrapper">
  <div class="container">
    <div class=row>
      <a href="projects/soretec.html">
        <div class="col-xs-12 col-sm-12 col-md-7 col-lg-7 card soretec no-padding">
          <div class="">
          </div>
        </div>
      </a>
      <a href="projects/archil.html">
        <div class="col-xs-12 col-sm-12 col-md-5 col-lg-5 card archil no-padding">
          <div class="">
          </div>
        </div>
      </a>
    </div>
    <div class=row>
      <a href="projects/ose.html">
        <div class="col-xs-12 col-sm-12 col-md-5 col-lg-5 card ose no-padding">
        </div>
      </a>
      <a href="projects/dmum.html">
        <div class="col-xs-12 col-sm-12 col-md-7 col-lg-7 card dmum no-padding">
        </div>
      </a>
    </div>
    <div class=row>
      <a href="projects/fermepc.html">
        <div class="col-xs-12 col-sm-12 col-md-7 col-lg-7 card fermepc no-padding">
        </div>
      </a>
      <a href="projects/pelemele.html">
        <div class="col-xs-12 col-sm-12 col-md-5 col-lg-5 card pelemele no-padding">
        </div>
      </a>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<h1>Projects#new</h1>
<p>Find me in app/views/projects/new.html.erb</p>

app/views/projects/ose.html.erb
<%= render 'shared/navbar-project' %>

<div class="body-project">

  <div class="container">

    <div class="row">
      <div class="col-xs-12, col-sm-12, col-md-8, col-lg-8 no-padding">
        <div class="photo-card" id="jersey-noir-ose">
        </div>
      </div>
      <div class="col-xs-12, col-sm-12, col-md-4, col-lg-4 no-padding">
        <div class="work-description">
          <h2>OSE - Opale Sports Équipements</h2>
          <h4>Création d'identité visuelle</h4>
          <p>- logo</p>
          <p>- carte de visite</p>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12, col-sm-12, col-md-4, col-lg-4 no-padding">
        <div class="photo-card-portrait" id="ose-cdv">
        </div>
      </div>
      <div class="col-xs-12, col-sm-12, col-md-4, col-lg-4 no-padding">
        <div class="work-description" id="jersey-bleu-ose">
        </div>
      </div>
      <div class="col-xs-12, col-sm-12, col-md-4, col-lg-4 no-padding">
        <div class="work-description" id="logo-ose">
        </div>
      </div>

    </div>
  </div>
</div>

app/views/projects/pelemele.html.erb
<%= render 'shared/navbar-project' %>

<div class="body-project">

  <div class="container">

    <div class="row">
      <div class="col-xs-12, col-sm-12, col-md-8, col-lg-8 no-padding">
        <div class="photo-card" id="mock-fp">
        </div>
      </div>
      <div class="col-xs-12, col-sm-12, col-md-4, col-lg-4 no-padding">
        <div class="work-description">
          <h2>FAIRE PART DE NAISSANCE</h2>
          <h4>Illustrations</h4>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12, col-sm-12, col-md-4, col-lg-4 no-padding">
        <div class="work-description" id="page1-fp">
        </div>
      </div>
      <div class="col-xs-12, col-sm-12, col-md-4, col-lg-4 no-padding">
        <div class="work-description" id="page2-fp">
        </div>
      </div>
      <div class="col-xs-12, col-sm-12, col-md-4, col-lg-4 no-padding">
        <div class="work-description" id="page3-fp">
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12, col-sm-12, col-md-4, col-lg-4 no-padding">
      <div class="work-description">
        <h2>ANAENSAIA - Association d'anciens élèves</h2>
        <h4>Création d'un logo</h4>
        <h4>Mise en page et graphisme d'un livret</h4>
      </div>
    </div>
      <div class="col-xs-12, col-sm-12, col-md-8, col-lg-8 no-padding">
        <div class="work-description" id="couv-ag">
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12, col-sm-12, col-md-6, col-lg-6 no-padding">
        <div class="photo-card" id="logo-ag">
        </div>
      </div>
      <div class="col-xs-12, col-sm-12, col-md-6, col-lg-6 no-padding">
        <div class="photo-card" id="double-ag">
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12, col-sm-12, col-md-8, col-lg-8 no-padding">
        <div class="work-description" id="mock-anasa">
        </div>
      </div>
      <div class="col-xs-12, col-sm-12, col-md-4, col-lg-4 no-padding">
        <div class="work-description">
          <h2>ANASA - Agence de voyage (fictive)</h2>
          <h4>Création d'une identité visuelle</h4>
          <h4>Affiches</h4>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12, col-sm-12, col-md-6, col-lg-6 no-padding">
        <div class="photo-card" id="multi-anasa">
        </div>
      </div>
      <div class="col-xs-12, col-sm-12, col-md-6, col-lg-6 no-padding">
        <div class="photo-card" id="lion-anasa">
        </div>
      </div>
    </div>

  </div>
</div>

app/views/projects/soretec.html.erb
<%= render 'shared/navbar-project' %>

<div class="body-project">

  <div class="container">

    <div class="row">
      <div class="col-xs-12, col-sm-12, col-md-8, col-lg-8 no-padding">
        <div class="photo-card" id="soretec-cdv">
        </div>
      </div>
      <div class="col-xs-12, col-sm-12, col-md-4, col-lg-4 no-padding">
        <div class="work-description">
          <h2>SORETEC - Bureau d'études</h2>
          <h4>Refonte d'identité visuelle</h4>
          <p>- logo</p>
          <p>- carte de visite</p>
          <h4>Mise en page d'un album de chantier</h4>
          <h4>Retouches photo</h4>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12, col-sm-12, col-md-4, col-lg-4 no-padding">
        <div class="photo-card" id="soretec-paper">
        </div>
      </div>
      <div class="col-xs-12, col-sm-12, col-md-8, col-lg-8 no-padding">
        <div class="work-description" id="soretec-dessin">
        </div>
      </div>
    </div>

  </div>

</div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer-wrapper">

    <div>
      <ul class="list-inline text-center">
        <li><a href="https://www.facebook.com/celia.albano.graphisme/" target="_blank"><i class="fa fa-facebook-square fa-2x" aria-hidden="true"></i></a></li>
        <li><a href="https://www.linkedin.com/in/celia-albano-aaa60220/" target="_blank"><i class="fa fa-linkedin-square fa-2x" aria-hidden="true"></i></a></li>
        <li><a href="https://www.behance.net/tsetsealbaa413" target="_blank"><i class="fa fa-behance-square fa-2x" aria-hidden="true"></i></a></li>
        <li><a href="https://www.instagram.com/celia.albano/" target="_blank"><i class="fa fa-instagram fa-2x" aria-hidden="true"></i></a></li>
      </ul>
    </div>

    <div>
      <p class="text-center">© Celia Albano Graphisme 2017</p>
    </div>

  </div>
</footer>

app/views/shared/_navbar-project.html.erb
<div class="navbar1">
  <!-- Logo -->
  <div class="logo-navbar">
    <a href="/"><img src="http://res.cloudinary.com/dusxpvpz7/image/upload/v1490695839/logo_w4whbz.png" style="width:70px"; alt="logo"></a>
    <h1>Celia Albano</br>Graphisme</h1>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-right hidden-xs hidden-sm">

    <!-- Projects link -->
    <a href="/#projets" class="nav-link">Projets</a>
<!--     <%= link_to 'Projets', projects_path, class: "nav-link" %>
 -->
    <!-- Contact link -->
    <a href="/#contact" class="nav-link">Contact</a>
<!--     <%= link_to 'Contact', contact_path, class: "nav-link" %>
 -->
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-dropdown-menu">
        <li><a href="/#projets" class="nav-link">Projets</a></li>
        <li><a href="/#contact" class="nav-link">Contact</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <div class="logo-navbar">
    <a href="/"><img src="http://res.cloudinary.com/dusxpvpz7/image/upload/v1490695839/logo_w4whbz.png" style="width:70px"; alt="logo"></a>
    <h1>Celia Albano</br>Graphisme</h1>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Projects link -->
    <a href="#projets" class="nav-link">Projets</a>
<!--     <%= link_to 'Projets', projects_path, class: "nav-link" %>
 -->
    <!-- Contact link -->
    <a href="#contact" class="nav-link">Contact</a>
<!--     <%= link_to 'Contact', contact_path, class: "nav-link" %>
 -->
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#projets" class="nav-link">Projets</a></li>
        <li><a href="#contact" class="nav-link">Contact</a></li>
      </ul>
    </div>
  </div>
</div>